import { supabase } from '../../config/supabase';
import { researchAgent } from '../research-agent/research.agent';
import { teacherAgent } from '../teacher-agent/teacher.agent';
import { quizAgent } from '../quiz-agent/quiz.agent';
import { codingAgent } from '../coding-agent/coding.agent';
import { revisionAgent } from '../revision-agent/revision.agent';

export interface OrchestrationParams {
  sessionId: string;
  userId: string;
  prompt: string;
  topic: string;
  difficulty: string;
  durationDays: number;
  learningStyle: string;
  language: string;
}

export class MasterAgent {
  /**
   * Run the multi-agent pipeline
   */
  async orchestrate(params: OrchestrationParams): Promise<any> {
    const { sessionId, userId, prompt, topic, difficulty, durationDays, learningStyle, language } = params;

    console.log(`>>> [Master Orchestrator] Starting session: ${sessionId} for user: ${userId}`);
    
    // Update session status to processing
    await supabase
      .from('learning_sessions')
      .update({ status: 'processing' })
      .eq('id', sessionId);

    try {
      // --- STAGE 1: RESEARCH AGENT ---
      const researchLogId = await this.logAgentStart(sessionId, 'Research');
      const concepts = await researchAgent.execute(topic, difficulty);
      await this.logAgentComplete(researchLogId, `Identified ${concepts.length} key learning concepts.`);

      // --- STAGE 2: TEACHER AGENT (Curriculum syllabus mapping) ---
      const curriculumLogId = await this.logAgentStart(sessionId, 'Curriculum');
      const syllabus = await teacherAgent.generateSyllabus(concepts, durationDays, difficulty);
      
      // Create Course
      const { data: course, error: courseErr } = await supabase
        .from('courses')
        .insert({
          session_id: sessionId,
          user_id: userId,
          title: `Mastery: ${topic}`,
          description: `Customized roadmap generated by the Master Orchestrator for "${prompt}".`,
          difficulty_level: difficulty,
          cover_image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600'
        })
        .select()
        .single();

      if (courseErr) throw courseErr;

      // Create course modules (days)
      const insertedModules = [];
      for (const day of syllabus) {
        const { data: moduleObj, error: modErr } = await supabase
          .from('course_modules')
          .insert({
            course_id: course.id,
            title: day.title,
            description: day.description,
            order_index: day.day_number,
            estimated_minutes: day.estimated_minutes
          })
          .select()
          .single();

        if (modErr) throw modErr;
        insertedModules.push(moduleObj);
      }
      await this.logAgentComplete(curriculumLogId, `Created syllabus with ${insertedModules.length} lessons.`);

      // --- STAGE 3: SPECIALIZED AGENTS EXECUTION ---
      // Determine if coding exercises are needed
      const needsCoding = this.detectCodingRequirement(topic, prompt);
      console.log(`>>> [Master Orchestrator] Coding exercises planned: ${needsCoding}`);

      // We process each module/day
      for (const moduleObj of insertedModules) {
        // 3.1 Teacher notes agent
        const teacherLogId = await this.logAgentStart(sessionId, `Teacher - Module ${moduleObj.order_index}`);
        const notesData = await teacherAgent.generateStudyNotes(moduleObj.title, difficulty);
        await supabase.from('notes').insert({
          module_id: moduleObj.id,
          content: notesData.content,
          key_takeaways: notesData.key_takeaways
        });
        await this.logAgentComplete(teacherLogId, `Study notes generated for "${moduleObj.title}".`);

        // 3.2 Quiz agent
        const quizLogId = await this.logAgentStart(sessionId, `Quiz - Module ${moduleObj.order_index}`);
        const questions = await quizAgent.execute(moduleObj.title);
        const { data: quizObj, error: qErr } = await supabase
          .from('quizzes')
          .insert({
            module_id: moduleObj.id,
            title: `Quiz: ${moduleObj.title}`
          })
          .select()
          .single();

        if (!qErr && quizObj) {
          for (const q of questions) {
            await supabase.from('quiz_questions').insert({
              quiz_id: quizObj.id,
              question: q.question,
              options: q.options,
              correct_option_index: q.correct_option_index,
              explanation: q.explanation
            });
          }
        }
        await this.logAgentComplete(quizLogId, `Quiz questions populated for "${moduleObj.title}".`);

        // 3.3 Coding agent (if applicable)
        if (needsCoding) {
          const codingLogId = await this.logAgentStart(sessionId, `Coding - Module ${moduleObj.order_index}`);
          const codeChallenge = await codingAgent.execute(moduleObj.title);
          await supabase.from('coding_exercises').insert({
            module_id: moduleObj.id,
            title: codeChallenge.title,
            problem_statement: codeChallenge.problem_statement,
            initial_code: codeChallenge.initial_code,
            solution_code: codeChallenge.solution_code,
            test_cases: codeChallenge.test_cases
          });
          await this.logAgentComplete(codingLogId, `Coding exercises populated for "${moduleObj.title}".`);
        }

        // 3.4 Revision agent (Flashcards)
        const revisionLogId = await this.logAgentStart(sessionId, `Revision - Module ${moduleObj.order_index}`);
        const flashcards = await revisionAgent.execute(moduleObj.title);
        for (const card of flashcards) {
          await supabase.from('flashcards').insert({
            user_id: userId,
            session_id: sessionId,
            front: card.front,
            back: card.back
          });
        }
        await this.logAgentComplete(revisionLogId, `Revision flashcards populated for "${moduleObj.title}".`);
      }

      // Mark session as complete
      await supabase
        .from('learning_sessions')
        .update({ status: 'completed' })
        .eq('id', sessionId);

      console.log(`>>> [Master Orchestrator] Session orchestration successfully completed.`);
      return {
        courseId: course.id,
        modulesCount: insertedModules.length
      };

    } catch (error: any) {
      console.error(`>>> [Master Orchestrator] Orchestration failed:`, error);
      
      // Update session status to failed
      await supabase
        .from('learning_sessions')
        .update({ status: 'failed' })
        .eq('id', sessionId);

      throw error;
    }
  }

  private async logAgentStart(sessionId: string, agentName: string): Promise<string> {
    const { data, error } = await supabase
      .from('agent_executions')
      .insert({
        session_id: sessionId,
        agent_name: agentName,
        status: 'running',
        started_at: new Date().toISOString()
      })
      .select('id')
      .single();

    if (error) throw error;
    return data.id;
  }

  private async logAgentComplete(logId: string, summary: string): Promise<void> {
    await supabase
      .from('agent_executions')
      .update({
        status: 'completed',
        output_summary: summary,
        completed_at: new Date().toISOString()
      })
      .eq('id', logId);
  }

  private detectCodingRequirement(topic: string, prompt: string): boolean {
    const keywords = [
      'code', 'program', 'python', 'javascript', 'typescript', 'react', 'rust',
      'c++', 'java', 'sql', 'backend', 'frontend', 'develop', 'api', 'algorithm',
      'data structures', 'docker', 'kubernetes', 'html', 'css', 'programming'
    ];
    const text = `${topic} ${prompt}`.toLowerCase();
    return keywords.some(keyword => text.includes(keyword));
  }
}

export const masterAgent = new MasterAgent();
export default masterAgent;
